nodeLinker: pnpm

npmRegistryServer: "https://packagefeedproxy.microsoft.io/npm/"

packageExtensions:
  "@ai-sdk/provider-utils@*":
    dependencies:
      zod: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
